### ISSUE TITLE
Create Design

### ISSUE THREAD

**Issue by YeyoM** [YeyoM/wellness-landing#1]

**Comment by Letalandroid** [comment]
# :zap: First Issue
Diseño completado con un pequeño detalle y una pequeña añadida.

## 🏁 Resultado
https://github.com/YeyoM/wellness-landing/assets/78810527/473651cc-8a9c-4967-8730-f9ac378d5d18

## 🕐
Como se puede ver la pequeña añadida fue la del pequeño cronometro sólo para dar una experiencia visual y junto con ello agregado de animaciones `scale de 1.5`, además del cambio en el color y tamaño de la barra de scroll.

**Comment by YeyoM** [comment]
Nice! Abre la PR para revisarla
