### ISSUE TITLE
En version Movil los features se pueden presionar, mantenerlos fijos.

### ISSUE THREAD

**Issue by Hofmann101** [YeyoM/wellness-landing#13]

**Comment by Letalandroid** [comment]
# 🧊 In mobile

El hover será deshabilitados para mobile y sólo se activarán a una cierta resolución para no tener animaciones sin concluir dentro de los usuarios mobile

## 🏁 Resultado

https://github.com/YeyoM/wellness-landing/assets/78810527/d23dac6b-842b-4fdd-99b9-f2d764d7b139
