### ISSUE TITLE
Habilitar Web analytics 

### ISSUE THREAD

**Issue by YeyoM** [YeyoM/wellness-landing#14]
Para esto, 

1. Instalar el package proporcionado por vercel
```bash
npm i @vercel/analytics
```
2. Agregar el siguiente componente a la app
```javascript
import { Analytics } from "@vercel/analytics/react"
```
Toda la documentación aquí https://vercel.com/docs/analytics/quickstart#add-the-analytics-component-to-your-app

**Comment by Letalandroid** [comment]
# 📶 Add Analytics into `./src/pages/Home.tsx`

Home.tsx `line 32`
```tsx
import { Analytics } from '@vercel/analytics/react';
```

Home.tsx `line 264`
```tsx
<Footer />
<Analytics />
```
