### ISSUE TITLE
Create animation when pressing "enviar"

### ISSUE THREAD

**Issue by YeyoM** [YeyoM/wellness-landing#3]
Create animation when pressing "enviar"
![Mon Mar  4 04:48:06 PM CST 2024](https://github.com/YeyoM/wellness-landing/assets/76639199/fe9e3dd5-a7ef-4762-aaea-14891d0c32fa)

**Comment by Letalandroid** [comment]
# 🎨Agregando el smooth al CSS para mejor visualización al interactuar con el botón `Unete ya!`

En: `./src/App.css` 

### Antes:
```css
body {
    scroll-behavior: smooth;
}
```

### Después:
```css
html {
    scroll-behavior: smooth;
}
```

Al momento de estar realizando el `smooth`, no me acordaba que se debía aplicar al padre en esta situación para que maneje el movimiento al deslizar la página al dar click al botón.

# 📧Consultar con Firebase
He dejado en el último commit, una simple conexión para obtener resultados de respuesta por si da error o caso contrario es satisfactoria la consulta.

En este caso el botón está a la escucha de envío del correo para ser enviado a una url obteniendo como respuesta, una positiva o una negativa.

```tsx
  const [email, setEmail] = useState('');
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState(false);

  const sendData = async () => {
    const res = await fetch('firebase_url', {
	headers: {
	  Accept: 'application/json',
	  'Content-type': 'aplication/json',
	},
	body: JSON.stringify({ email }),
    });

    const data = await res.json();

    if (data.error) {
      setError(true);
    } else {
      setSuccess(true);
    }
  };

<button onClick={sendData} className="bg-black text-white px-10 py-3 rounded-2xl transition hover:bg-white hover:text-black">Enviar</button>

{error ? (
  <p className="text-sm text-red-600 font-bold">Parece ser que el correo que intentas enviar, ya ha sido </p>
) : (
<>
  {success ? (
    <p className="text-green-500 font-bold">¡Registro enviado correctamente!</p>
) : ( '' )} </>)}
```

# 📼Resultado 
https://github.com/YeyoM/wellness-landing/assets/78810527/0d7cbd9d-4995-4d16-ae9b-476890490496

**Comment by YeyoM** [comment]
Nice! Abre la PR para aprobarla! @Letalandroid
