### ISSUE TITLE
Create fireabase functionalities

### ISSUE THREAD

**Issue by YeyoM** [YeyoM/wellness-landing#4]
When pressing the button "enviar", a firebase function should be triggered to and save to our database a document in the "users-beta" collection, with auto-generated id, and only store the email. Achieve this using transactions.

1. Install firebase using npm, then configure firebase in the project in a file called firebaseConfig.js or ts like so: https://github.com/YeyoM/wellness-mobile-app/blob/master/firebaseConfig.js, using the env variables.

2. Create a function in a separate file called registerBetaTester.js or ts, this function should take an email as parameter, if the email was already registered, throw an error, if the email is registered correctly, return nothing. *This function should include should detect if the input is a valid email.

3. Integrate the function to accept the prompt from the user, if the user tries to send an invalid email or the email was already taken or an error occurs, show an error notification to the user. If the email is correct, and it is registered correctly, show the user a success notification.

![Mon Mar  4 04:57:33 PM CST 2024](https://github.com/YeyoM/wellness-landing/assets/76639199/52489f63-0dad-491b-8e75-8a58aef58c2c)

![Mon Mar  4 04:57:52 PM CST 2024](https://github.com/YeyoM/wellness-landing/assets/76639199/4f1f148e-d3e4-4092-bfe6-d8ccef128682)

**Comment by YeyoM** [comment]
@Letalandroid to get access to the firebase dashboard in order to check if the user was indeed saved, please reach out to @Hofmann101 for the corresponding credentials

**Comment by YeyoM** [comment]
Docs: https://firebase.google.com/docs/firestore/manage-data/transactions
Examples: https://github.com/YeyoM/wellness-mobile-app/blob/master/FirebaseFunctions/Routines/createRoutine.js

**Comment by Letalandroid** [comment]
# Create fireabase functionalities 🔧

Teniendo al completo el tema de la funcionalidad y comunicación con la bd en firebase para guardar el correo de los usuarios, estaría lista con pequeños cambios al ejemplo en [3-create-animation-when-pressing-enviar](https://github.com/YeyoM/wellness-landing/tree/3-create-animation-when-pressing-enviar).

## 🎨 Propuesta de diseño para botón Enviar
```tsx
<button className="bg-black text-white px-10 py-3 rounded-2xl transition hover:bg-white hover:text-black">
  { loading ? <HashLoader color={'#fff'} size={18} /> : 'Enviar' }
</button>
```
La libreria [react-spinners](https://www.davidhu.io/react-spinners/) nos permite colocar íconos de carga, la cuál utilice para una mejor UX y darle a comunicar al usuario que estamos a la espera de la respuesta del servidor.

---
Este sería un resumen del cambio en cuánto al code de comunicación y ejecución para las tareas a realizar en Firebase.

### App.ts
```tsx
const onSubmit = handleSubmit(async () => {
  setLoading(true);
  setError(false);
  setSuccess(false);
  const emailExists = await getAll(email, setError);

  if (!emailExists) {
    setError(false);
    await registerUser(email, setSuccess);
  }
  setLoading(false);
});
```

- ### getAll() [RegisterBetaTester.ts]
```tsx
export const getAll = async (
  email: string,
  setError: React.Dispatch<React.SetStateAction<boolean>>
) => {
  const querySnapshot = await getDocs(collection(db, 'users-beta'));
  let emailExists = false;
  querySnapshot.forEach((doc) => {
  if (doc.data().email === email) {
      emailExists = true;
      setError(true);
      console.error('⛔ El correo electrónico ya se encuentra registrado.');
      return;
    }
  });
  return emailExists;
};
```

- ### registerUser() [RegisterBetaTester.ts]
```tsx
export const registerUser = async (
  email: string,
  setSuccess: React.Dispatch<React.SetStateAction<boolean>>
) => {
  const ref = collection(db, 'users-beta');
  await addDoc(ref, { email })
  .then(() => {
    setSuccess(true);
    console.log('✅ Solicitud enviada correctamente.');
  }).catch((error) => console.error('⛔ Error:', error));
};
```

## 📼 Resultado
https://github.com/YeyoM/wellness-landing/assets/78810527/3a5b10b1-1ff3-4194-b32d-e66a01a419c9

**Comment by YeyoM** [comment]
Nice! Haz la PR y la apruebo @Letalandroid
